### ISSUE TITLE
パスに日本語が含まれていると動作しない

### ISSUE THREAD

**Issue by eliza0x** [mattn/goemon#10]
いつも資料を作成するときにPandocと組み合わせて使わせていただいでいます。
詳しくはテストしていないのですが、パスに日本語が含まれていると、どうもうまく動作しない気がします。
環境はArch Linux, LANG=en_US.UTF-8です

**Comment by mattn** [comment]
ありがとうございます。ちなみにどの様なパスでしょうか？

On 4/23/17, Sohei Yamaga <notifications@github.com> wrote:
> いつも資料を作成するときにPandocと組み合わせて使わせていただいでいます。
> 詳しくはテストしていないのですが、パスに日本語が含まれていると、どうもうまく動作しない気がします。
> 環境はArch Linux, LANG=en_US.UTF-8です
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/goemon/issues/10


-- 
- Yasuhiro Matsumoto

**Comment by eliza0x** [comment]
~/Docs/講義/科学/第一回 のようなパスです

**Comment by mattn** [comment]
ありがとうございます。あとで検証します。

**Comment by mattn** [comment]
手元で ubuntu を使い `goemon -g md` で出力した goemon.yml を `**/*.md` に変更、その後 `goemon -a :5000` で起動した状態で md ファイルを編集した時のスクリーンショットです。

![goemon](http://go-gyazo.appspot.com/8024e52c7d6b6d6b.png)

今のところ問題なく動いている様にみえます。なにか特別な設定など無いでしょうか？

**Comment by eliza0x** [comment]
特別な設定は特にしていないように思いますが、matchの*か**が怪しい気がします、他設定には{GOEMON_TARGET_NAME}か{GOEMON_TARGET_FILE}を使っているぐらいでしょうか

**Comment by mattn** [comment]
ちなみにうまく動かないというのはどの様な動作でしょうか？

**Comment by eliza0x** [comment]
matchでマッチしていないかしているけど動作しない、だと思います

**Comment by mattn** [comment]
pandoc が走らないという事で良いでしょうか？

**Comment by eliza0x** [comment]
ええ、そうです
シェルスクリプト単体だと思ったとおりの動作はしました

**Comment by mattn** [comment]
設定ファイルを見せて貰って良いでしょうか。あとそのファイルがどこに置かれているのかも教えて下さい。

**Comment by eliza0x** [comment]
設定ファイルはこちらの都合で後日になります、すみません
パスは `~/Dropbox/Documents/講義/2017/生命科学/` で、マッチしないのがそれ以下のディレクトリ内のファイルです

**Comment by eliza0x** [comment]
設定ファイルです

```
# Generated by goemon -g
livereload: :35730
tasks:
- match: './**/*.markdown'
  commands:
  - pandoc -s -c ./gruvbox_customize.syntax.css --template ./html5.template.html -t html5 -o ./html/${GOEMON_TARGET_NAME}.html ${GOEMON_TARGET_FILE}
  - :livereload /
- match: './goemon.yaml'
  commands:
  - :restart
  - :livereload /
- match: './*.syntax.css'
  commands:
  - :restart
  - :livereload /
- match: './*.template.html'
  commands:
  - :restart
  - :livereload /
```
